services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_school
    ports:
      - "5672:5672"      # Порт для подключения (AMQP)
      - "15672:15672"    # Порт для веб-интерфейса (Management UI)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:7-alpine
    container_name: redis_school
    ports:
      - "6379:6379"      # Порт для подключения
    volumes:
      - redis_data:/data

volumes:
  rabbitmq_data:
  redis_data: